
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftSOMASUBleftMULTDIVrightPOTrightUMINUSDIV FUNCAO ID IGUAL LPAREN MULT NUMERO POT RPAREN SOMA SUB VIRGULAprograma : declaracoesdeclaracoes : declaracoes declaracao\n| declaracaodeclaracao : declaracao_funcao\n| atribuicaodeclaracao_funcao : FUNCAO ID LPAREN params RPAREN IGUAL expressaoparams : params VIRGULA ID\n| ID\n| emptyatribuicao : ID IGUAL expressaoexpressao : expressao SOMA expressao\n| expressao SUB expressao\n| expressao MULT expressao\n| expressao DIV expressao\n| expressao POT expressaoexpressao : SUB expressao %prec UMINUSexpressao : LPAREN expressao RPARENexpressao : ID LPAREN args RPARENargs : args VIRGULA expressao\n| expressao\n| emptyexpressao : NUMEROexpressao : IDempty :'
    
_lr_action_items = {'FUNCAO':([0,2,3,4,5,8,12,13,16,26,33,34,35,36,37,38,41,43,],[6,6,-3,-4,-5,-2,-23,-10,-22,-16,-11,-12,-13,-14,-15,-17,-18,-6,]),'ID':([0,2,3,4,5,6,8,10,11,12,13,14,15,16,20,21,22,23,24,25,26,29,33,34,35,36,37,38,39,41,42,43,],[7,7,-3,-4,-5,9,-2,12,17,-23,-10,12,12,-22,12,12,12,12,12,12,-16,40,-11,-12,-13,-14,-15,-17,12,-18,12,-6,]),'$end':([1,2,3,4,5,8,12,13,16,26,33,34,35,36,37,38,41,43,],[0,-1,-3,-4,-5,-2,-23,-10,-22,-16,-11,-12,-13,-14,-15,-17,-18,-6,]),'IGUAL':([7,28,],[10,39,]),'LPAREN':([9,10,12,14,15,20,21,22,23,24,25,39,42,],[11,15,20,15,15,15,15,15,15,15,15,15,15,]),'SUB':([10,12,13,14,15,16,20,21,22,23,24,25,26,27,31,33,34,35,36,37,38,39,41,42,43,44,],[14,-23,22,14,14,-22,14,14,14,14,14,14,-16,22,22,-11,-12,-13,-14,-15,-17,14,-18,14,22,22,]),'NUMERO':([10,14,15,20,21,22,23,24,25,39,42,],[16,16,16,16,16,16,16,16,16,16,16,]),'RPAREN':([11,12,16,17,18,19,20,26,27,30,31,32,33,34,35,36,37,38,40,41,44,],[-24,-23,-22,-8,28,-9,-24,-16,38,41,-20,-21,-11,-12,-13,-14,-15,-17,-7,-18,-19,]),'VIRGULA':([11,12,16,17,18,19,20,26,30,31,32,33,34,35,36,37,38,40,41,44,],[-24,-23,-22,-8,29,-9,-24,-16,42,-20,-21,-11,-12,-13,-14,-15,-17,-7,-18,-19,]),'SOMA':([12,13,16,26,27,31,33,34,35,36,37,38,41,43,44,],[-23,21,-22,-16,21,21,-11,-12,-13,-14,-15,-17,-18,21,21,]),'MULT':([12,13,16,26,27,31,33,34,35,36,37,38,41,43,44,],[-23,23,-22,-16,23,23,23,23,-13,-14,-15,-17,-18,23,23,]),'DIV':([12,13,16,26,27,31,33,34,35,36,37,38,41,43,44,],[-23,24,-22,-16,24,24,24,24,-13,-14,-15,-17,-18,24,24,]),'POT':([12,13,16,26,27,31,33,34,35,36,37,38,41,43,44,],[-23,25,-22,-16,25,25,25,25,25,25,25,-17,-18,25,25,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'declaracoes':([0,],[2,]),'declaracao':([0,2,],[3,8,]),'declaracao_funcao':([0,2,],[4,4,]),'atribuicao':([0,2,],[5,5,]),'expressao':([10,14,15,20,21,22,23,24,25,39,42,],[13,26,27,31,33,34,35,36,37,43,44,]),'params':([11,],[18,]),'empty':([11,20,],[19,32,]),'args':([20,],[30,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> declaracoes','programa',1,'p_programa','parser.py',16),
  ('declaracoes -> declaracoes declaracao','declaracoes',2,'p_declaracoes','parser.py',20),
  ('declaracoes -> declaracao','declaracoes',1,'p_declaracoes','parser.py',21),
  ('declaracao -> declaracao_funcao','declaracao',1,'p_declaracao','parser.py',28),
  ('declaracao -> atribuicao','declaracao',1,'p_declaracao','parser.py',29),
  ('declaracao_funcao -> FUNCAO ID LPAREN params RPAREN IGUAL expressao','declaracao_funcao',7,'p_declaracao_funcao','parser.py',33),
  ('params -> params VIRGULA ID','params',3,'p_params','parser.py',37),
  ('params -> ID','params',1,'p_params','parser.py',38),
  ('params -> empty','params',1,'p_params','parser.py',39),
  ('atribuicao -> ID IGUAL expressao','atribuicao',3,'p_atribuicao','parser.py',48),
  ('expressao -> expressao SOMA expressao','expressao',3,'p_expressao_binop','parser.py',52),
  ('expressao -> expressao SUB expressao','expressao',3,'p_expressao_binop','parser.py',53),
  ('expressao -> expressao MULT expressao','expressao',3,'p_expressao_binop','parser.py',54),
  ('expressao -> expressao DIV expressao','expressao',3,'p_expressao_binop','parser.py',55),
  ('expressao -> expressao POT expressao','expressao',3,'p_expressao_binop','parser.py',56),
  ('expressao -> SUB expressao','expressao',2,'p_expressao_uminus','parser.py',60),
  ('expressao -> LPAREN expressao RPAREN','expressao',3,'p_expressao_grupo','parser.py',64),
  ('expressao -> ID LPAREN args RPAREN','expressao',4,'p_expressao_chamada_funcao','parser.py',68),
  ('args -> args VIRGULA expressao','args',3,'p_args','parser.py',72),
  ('args -> expressao','args',1,'p_args','parser.py',73),
  ('args -> empty','args',1,'p_args','parser.py',74),
  ('expressao -> NUMERO','expressao',1,'p_expressao_numero','parser.py',83),
  ('expressao -> ID','expressao',1,'p_expressao_id','parser.py',87),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',91),
]
